### ISSUE TITLE
HtmlTag.Parse parses incorrect HTML Entities

### ISSUE THREAD

**Issue by hoangitk** [amoerie/HtmlBuilders#109]
When I test xss from a html Editor, I found HtmlTag.Parse/ParseAll works incorrect
Give `<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1>` (saved from html editor)

`HtmlTags.Div.Append(HtmlTag.Parse("<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1>")).ToHtmlString()`
❌ `<div><h1><strong>hello <img onerror="alert(0)" src="" /></strong></h1></div> ` (incorrect)
✅ `<div><h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1></di
/v>` (correct)

**Comment by amoerie** [comment]
Hi @hoangitk 

When you pass in raw HTML as a string, it is "de-entitized". This is by design. If you don't want this, you can bypass it by passing in your own TextReader that doesn't do de-entitization.

This is the source code of HtmlTag.Parse:

https://github.com/amoerie/HtmlBuilders/blob/7337dfd23a3bcf4637a7fe6b5d666e99d8bdb868/HtmlBuilders/HtmlTag.cs#L686-L691

As you can see, it de-entitizes the string, creates a StringReader and then calls this overload that accepts a TextReader:

https://github.com/amoerie/HtmlBuilders/blob/7337dfd23a3bcf4637a7fe6b5d666e99d8bdb868/HtmlBuilders/HtmlTag.cs#L704-L712

So, all you need to do is make your own StringReader, like this:

```csharp
        [Fact]
        public void WhenHtmlContainsXssShouldNotParse()
        {
            var input = "<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1>";
            using var reader = new StringReader(input);
            var parsed = HtmlTag.Parse(reader);
            parsed.ToHtmlString().Should().Be("<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1>");
        }
```

Yes, I could also remove the de-entitization, but that would be a major breaking change for everyone using this library.

**Comment by hoangitk** [comment]
@amoerie : Thanks for your guide!
I also find out **v6.01 (for .net 6.0)** generate different from 
Give: `<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1> (saved from html editor)`
A: `HtmlTags.Div.Append(new HtmlString("<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1>")).ToHtmlString();`
B: `HtmlTags.Div.Append(HtmlTag.Parse("<h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1>")).ToHtmlString();`
+ v7.2.0
A:`<div><h1><strong>hello &lt;img src onerror=alert(0) /&gt;</strong></h1></div>` 👍
B:`<div><h1><strong>hello <img onerror="alert(0)" src="" /></strong></h1></div`
+ v6.0.1
A:`<div><h1><strong>hello <img onerror="alert(0)" src="" /></strong></h1></div>` ☹️
B:`<div><h1><strong>hello <img onerror="alert(0)" src="" /></strong></h1></div>`

Would you mind giving any guide for v6.0.1? Thank you!

**Comment by hoangitk** [comment]
nvm, I am lazy. I fixed by your guide. Thank you so much!

public static HtmlTag AppendRawHtml(this HtmlTag tag, string htmlContent)
{
  using var reader = new StringReader(htmlContent);
  var parsed = HtmlTag.Parse(reader);
  tag = tag.Append(parsed);
  return tag;
}
