### ISSUE TITLE
Html Doctype

### ISSUE THREAD

**Issue by AceTheWiz** [amoerie/HtmlBuilders#57]
How do I create the ```<!DOCTYPE html>``` "tag"

**Comment by amoerie** [comment]
Hmm I never really used HtmlBuilders for full HTML documents, Razor is better for that.

DOCTYPE isn't really an HTML tag either, because it can't have attributes or children.

I think the easiest way would be to use new HtmlText(new HtmlString(....)) and write it to the output like that. Both HtmlTag and HtmlText inherit from IHtmlElement if you need to put them in a list or so.

**Comment by AceTheWiz** [comment]
Ok, thanks I will try that.
